### ISSUE TITLE
[28] IB - 2015.01.26

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#110]

**Comment by JRice** [comment]
I thought it would perhaps be useful to put some of the actual interrupts into this ticket, for posterity...

Yesterday was _entirely_ spent (for me) on the quarterly patching. I took some notes while doing it, so it should be a little less painful next time. But, of note:
- Notifications failed because it was using an old version of the resque container and was missing a gem update (I had manually updated it before the patching). I've since re-built that container, so it shouldn't happen again.
- We could have patched app2 on the previous day. Next quarter, we should add smasher and archive to the first batch.
- Taking down the eol1 container was ... broken. It doesn't come down cleanly, and docker doesn't stop cleanly. I _think_ (this is a guess) that's because of the docker logs that are being stored on these machines: it's a _ridiculous_ amount of data, and I think it's trying to clear all of it. We don't need the logs as-is, we should change the way these are written. Anyway, this caused the second batch of servers to take longer than two hours to finish!
- Next quarter, we should change the passwords for the database.
- the ulimit was 1024 on the SQL servers! This eventually causes BIG problems. We were lucky not to lose data this time! ...Anyway, solving this was as simple as stopping and re-starting docker. Something to watch for, next time.
- I remembered to turn off Solr's logging. ;)
- All of the "eol" based containers (including resque) have incorrect permissions in root after coming up. This can cause them to die entirely (but not close; they're just zombie-ish), so this is something we should fix.
- I didn't have access to Amazon Web Services. ...I finally figured out why and got Dima to sign the "root account" over to me, though I haven't tried logging in with it yet. I will the next time I'm there.

...I also spent about a half-day on this on Wednesday, doing the first batch and prepping for the main batch. ...So we lose 1.5 days per quarter to patching, and it includes over 2 hours of downtime for EOL. A PITA.
