### ISSUE TITLE
[1] Document new TraitBank implementation

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#113]
Need to explain how the data is accessed, how it's stored in virtuoso, what methods and classes are relevant, etc.

**Comment by JRice** [comment]
Okay, this is done. See `doc/trait_bank.md` [in the project](https://github.com/EOL/eol/blob/master/doc/trait_bank.md).

**Comment by jhammock** [comment]
Thanks, J! Quick question from the resource wranglers- Measurement ID in the MeasurementOrFact file was not previously required. Is it now?

**Comment by JRice** [comment]
Oooooh... good question. I didn't realize that was optional, but: I'm not
getting it from the resource file, so whatever PHP is doing with it, that's
what the new system uses. So: it fine as-is, whatever it is.

If it were up to me: no, it would not be required; it would default to an
auto-incremented integer, which would be perfectly fine. If I recall (and I
could be wrong) it currently defaults to an MD5 hash of the text of the
whole line (I think the intent there was to ensure old data would have a
different ID than new data)... I don't like that, because I don't think we
should be keeping around old data ... but it doesn't matter at this point.
Something to handle in Tramea, though.

**Comment by jhammock** [comment]
If you haven't hit a resource where this was a problem, I expect whatever the PHP is doing will suffice- but feel free to require it if you prefer. @KatjaSchulz, I think, includes these IDs already, and I can conform.

**Comment by KatjaSchulz** [comment]
Yes, all my data resources have measurementIDs.
