### ISSUE TITLE
eol page search for "Brown" returns an (incorrect) exact match for Brown Wood Owl (Strix leptogrammica)

### ISSUE THREAD

**Issue by jhpoelen** [EOL/tramea#120]
see https://github.com/jhpoelen/eol-globi-data/issues/175

**Comment by YoustinaAtef** [comment]
Current status:
We can see this result because "Brown" is really one of this taxon concept's common names but we can't see this common name in names tab because its source_hierarchy_entry is unpublished.
Solution:
We should index names only from published hierarchy entries. 
We should handle this in the new harvest code and make sure that if any hierarchy entry become unpublished then we should re-index site search core.

**Comment by jhammock** [comment]
Thank you, Youstina! I'll make a note of this the EOL@10 feature doc (just in case the distinction is missed again. I expect it will have to wait for now.

**Comment by jhpoelen** [comment]
@jhammock I'd like to suggest to close issues only when the fixes are available in production. 

As far as I can tell, the issue is not yet fixed in the current production version.

**Comment by jhammock** [comment]
@JRice @jhpoelen  I _think_ milestone is the best facet to keep track of these things without either forgetting them or getting them mixed up in current or recent iterations. Let me know, because we will get more of these...

**Comment by jhpoelen** [comment]
Issue no longer seems to occur (see https://github.com/jhpoelen/eol-globi-data/issues/175).

@YoustinaAtef @JRice  thanks for the fix!
