### ISSUE TITLE
Random "Oops" Error messages/pages (add examples here)

### ISSUE THREAD

**Issue by mariestuder** [EOL/tramea#125]
"Oops pages" occur at random times. We can use this ticket to record them when they happen.

**Comment by holmesjtg** [comment]
Got an Oops today while trying to crop an image.

**Comment by jhammock** [comment]
Cropping errors are inconsistent. I just got a successful crop of http://eol.org/data_objects/22857304 

but then got this oops: http://eol.org/data_objects/15599151/crop?id=15599151&x=37.129629629629626&y=15.25389017489712&w=51.2962962962963&h=&commit=crop+image

**Comment by JRice** [comment]
Image cropping would succeed or fail (at the time those last two comments were written) based on where the original image was located. If it was an old image (most images), it would fail... if it was "new" image that was sitting on the PHP machine, it would work.

Anyway, it should now work in both places. This was a bug caused by the patching of the servers (because after patching, all containers are restarted, and that CAN cause code changes if there were custom, uncommitted changes before the patch... which clearly there were for PHP, sigh). Next quarter, I'll spend some additional time looking for differences on servers to try and avoid this happening again.

**Comment by JRice** [comment]
Worth noting: this issue with cropping is a stupid problem to have. The only reason we do this is because not all machines have access to content that can be served to the web. That's it: the only reason we have thousands of lines of complicated, brittle code.

We really should have a big old RAID drive on the network that all of these machines can write to. Period.

**Comment by jhammock** [comment]
(just cropped 10 images without incident, looks like we're good for now.)

**Comment by holmesjtg** [comment]
New oops error today... accessing this collection page:
http://www.eol.org/collections/120626

**Comment by jhammock** [comment]
@holmesjtg, can you give me an owner for the collection, and a resource if it's a partner collection? Thx

**Comment by holmesjtg** [comment]
Tis I (that is the owner), and it's a collection I made as a master collection for the other Galiano collections that I'm working on.

**Comment by JRice** [comment]
```
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    2: %ul#collection_items.object_list
    3:   - @collection_items.each do |item|
    4:     - item_type = en_type(item)
    5:     %li{class: item_type, id: "collection_item_#{item.id}"}
    6:       = render 'collection_items/show', { :collection_item => item, :item_type => item_type,
    7:         :view_style => 'annotated', :item_editable => editable,
    8:         is_hidden: ['image_map', 'map', 'image', 'video', 'sound', 'link', 'article'].include?(item_type) && item.is_hidden?  }
  app/views/collections/_show_annotated_style.html.haml:5:in `block in _app_views_collections__show_annotated_style_html_haml__2001904726292938680_44313980'
  app/views/collections/_show_annotated_style.html.haml:3:in `each'
  app/views/collections/_show_annotated_style.html.haml:3:in `_app_views_collections__show_annotated_style_html_haml__2001904726292938680_44313980'
  app/views/collections/show.html.haml:67:in `block in _app_views_collections_show_html_haml__34024609985757996_94564440'
  app/views/collections/show.html.haml:42:in `_app_views_collections_show_html_haml__34024609985757996_94564440'
```
