### ISSUE TITLE
The data object API seems to be broken

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#137]
From @kueda via the Contact Us form

The data object API seems to be broken. Requests for http://eol.org/api/data_objects/1.0/bb09e64dba013e398ad7dba07de617b0.json used to return details about the photo (in this case http://eol.org/data_objects/22663380), including URLs that we were using on iNaturalist, but now it's just includes some taxonomic info.

**Comment by HudaSoliman** [comment]
The fix is pushed on the master now.

**Comment by jhammock** [comment]
Thanks, @HudaSoliman ! @kueda, it looks like a nice detailed response to me; is everything you need back in there?

**Comment by jhammock** [comment]
I can't see the mediaURLs, myself; should they be in there full length, or are they constructed from identifiers?

**Comment by pleary** [comment]
FWIW, looks like the issue started in eol/eol@5c22fd00efb241979f8c8b56d1ac4a44bb5c9805 . If you tack on an images, text, sounds, etc parameter (e.g. http://eol.org/api/data_objects/1.0/bb09e64dba013e398ad7dba07de617b0.json?text=1) then you do see the media URLs because it appeases the conditional at https://github.com/EOL/eol/blob/master/lib/eol/api/pages/v1_0.rb#L201

**Comment by jhammock** [comment]
Good to know, thanks!

**Comment by pleary** [comment]
I see that this has been closed, but I am still not seeing any data object information at http://eol.org/api/data_objects/1.0/bb09e64dba013e398ad7dba07de617b0.json . I'm not sure if my comment was unclear, but I was indicating the bug still exists and pointing out where the bug is in the code. I also included a URL that demonstrated the bug in the code. This does not appear to be resolved yet.

**Comment by jhammock** [comment]
Oh... http://eol.org/api/data_objects/1.0/bb09e64dba013e398ad7dba07de617b0.json?images=1 is not a valid query? It returns media urls for this data object.

**Comment by pleary** [comment]
It shouldn't require the ?images=1, since the request is for a singular data object, so the type is inferred by the data object ID. For example take the nonsensical requests http://eol.org/api/data_objects/1.0/bb09e64dba013e398ad7dba07de617b0.json?sounds=1 or http://eol.org/api/data_objects/1.0/bb09e64dba013e398ad7dba07de617b0.json?videos=1 which return this _**image's**_ metadata.  http://eol.org/api/data_objects/1.0/bb09e64dba013e398ad7dba07de617b0.json should work on its own. At least it used to and thus the confusion from an API end-user perspective

**Comment by jhammock** [comment]
Got it, thx.
