### ISSUE TITLE
Curated Image jumped from one taxon to another

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#151]
```
Subject: A message to EOL: Technical questions (feedback or problems with functionality)
Date: February 8, 2016 at 1:52:31 PM EST
To: support@eol.org

The following message was submitted to EOL via the Contact Us form:
From: Dana Campbell
Subject: Technical questions (feedback or problems with functionality)

Eek.  I curated this image: http://eol.org/data_objects/24941648 on the Swamp Tupelo page (http://eol.org/pages/481860/media) and it disappeared.  Before curating, there were 30 media listed on the tab.  there are now 29.

Thanks,
Dana

http://eol.org/users/35329
```

**Comment by JRice** [comment]
Jen points out: "I was ready to assume the media galleries were out of date after hierarchy changes. FYI, I reindexed both the data object and the taxon page. That is when the media count dropped to 28. (I don’t know where the other image went, but I presume it’s on another taxon page somewhere) The two taxa are congeners and share a common name"

...It _does_ seem reasonable that a [Swamp Tupelo](http://eol.org/data_objects/24941648) could also "be" a [Black Tupelo](http://eol.org/pages/585634/overview)...

**Comment by KatjaSchulz** [comment]
Nyssa biflora Walter is a synonym of Nyssa sylvatica var. biflora (see: http://www.theplantlist.org/tpl1.1/record/kew-136191), i.e., it's a child of Nyssa sylvatica.  If you go to the Names tab of Nyssa biflora (http://eol.org/pages/481860/names), you'll see that somebody (probably I, actually) tried to do taxon concept management on this page.  It says "The classifications on this page cannot be edited at this time. Another request to edit these classifications is being processed."  My hypothesis is that I tried to merge Nyssa biflora with Nyssa biflora var. biflora, and some aspects of the merge happened, but it didn't go through all the way.  So now we have some weirdness in the database.  

The bad news is that taxon concept management hasn't been working for a while now, so we probably have some other weirdness resulting from attempted splits & merges.  The good news is that Dana's problem is probably not due to a glitch that's threatening the integrity of our entire names infrastructure.
