### ISSUE TITLE
Spreadsheet resources not recognized

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#185]
Spreadsheets can not presently be converted to DwC-A using http://services.eol.org/xls2dwca/   Nor loaded to EOL via the Content Partner system. The resource status reads "Uploading" indefinitely.

examples at:

http://eol.org/content_partners/630/resources/688
http://eol.org/content_partners/178/resources/972
http://eol.org/content_partners/178/resources/973
http://eol.org/content_partners/178/resources/974

**Comment by JRice** [comment]
Problem is in `ContentManager::download_temp_file_and_assign_extension`

Somewhat cryptic output:

```
02/26 15:00:36:: ContentManager: = download_temp_file_and_assign_extension ==========
02/26 15:00:36:: ContentManager: = 02/26 15:00:36:: ContentManager: = /var/www/eol_php_code/applications/content_server/tmp/b9df1b383499a777058b313642b4449c.file (from /tmp/php1GGX7c )
02/26 15:00:36:: Sending get request to file:///tmp/php1GGX7c : only attempt :: [lib/ContentManager.php [157]]
02/26 15:00:36:: ContentManager: got remote file :: [ []]
02/26 15:00:36:: ContentManager: wrote file :: [ []]
02/26 15:00:36:: ContentManager: is file (suffix xlsx) :: [ []]
02/26 15:00:36:: ContentManager: give_temp_file_right_extension :: [applications/xls2dwca/form_result.php [21]]
02/26 15:00:36:: ContentManager: file exists (original suffix xlsx) :: [applications/xls2dwca/form_result.php [21]]
02/26 15:00:36:: ContentManager: gave extension:  :: [ []]
02/26 15:00:36:: ContentManager: enforced extension:  :: [ []]
02/26 15:00:36:: Completed /var/www/xls2dwca/form_result.php :: [ []]
```

That temp file it mentions is, in fact, there, and its contents look reasonable-ish (binary).

**Comment by JRice** [comment]
Actually, the problem seems to be with `give_temp_file_right_extension` which is returning a null string. That, in turn, points to `determine_file_suffix`, which is also returning null. Looks like it might be the FILE_BIN_PATH (which defaults to 'file') that's not working properly.

On our temp file, that returns:

```
/var/www/eol_php_code/applications/content_server/tmp/b9df1b383499a777058b313642b4449c.file: Microsoft Excel 2007+
```

...There was a small problem in ContentManager. I've fixed it. ...but there's now another problem.

**Comment by JRice** [comment]
Okay, I'm now 85% sure that the problem is actually with the `ExcelToText` library. The `canRead` method returns false. I've tried as .xls and .xlsx; neither work.

This is disturbing. I don't see a quick way around this. ...We should file a ticket to let BA try working on this particular problem (noting that the work must be done ON THE HARVESTING SERVER AT SI, because I suspect the problem is the libraries used there, since this works fine locally), and in the meantime we may have to insist on DWCa files. :S

Not good. I hope this is a simpler problem to solve than I fear.

**Comment by JRice** [comment]
(It's also possible that the format of the file I was trying was bad, but I did copy it from a resource that we used to parse (at Harvard), so that'd be surprising. The file type is listed as "Excel 2007+", if that means anything.)

**Comment by jhammock** [comment]
If you want to check another file, [here](https://www.dropbox.com/s/xg5iisxwcl2tth6/Sal%202013.xlsx?dl=0) is a TB era spreadsheet that really aught to work

**Comment by jhammock** [comment]
exceltotext investigation in https://github.com/EOL/tramea/issues/217

replacement service under construction in https://github.com/EOL/tramea/issues/223

**Comment by jhammock** [comment]
See https://github.com/EOL/tramea/issues/217
