### ISSUE TITLE
metadata missing from TB records

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#253]
I think one of these may be a metadata field we haven't hit before. The other I have no theory for. They're in http://eol.org/content_partners/709/resources/804

all records (eg: http://eol.org/pages/23284/data#data_point_9529372) should have both the following fields:

http://rs.tdwg.org/dwc/terms/measurementDeterminedBy    is a field we may not have harvested yet in New TB

http://purl.org/dc/terms/source    we certainly have in other resources, eg: http://eol.org/pages/1179469/data#data_point_847556

**Comment by JRice** [comment]
Huh.

For that data point you reference, there are only the following predicates associated with it:

http://www.w3.org/1999/02/22-rdf-syntax-ns#type = http://rs.tdwg.org/dwc/terms/MeasurementOrFact
http://www.w3.org/1999/02/22-rdf-syntax-ns#type = http://eol.org/schema/trait
http://rs.tdwg.org/dwc/terms/measurementType = http://www.owl-ontologies.com/unnamed.owl#Colonial
http://rs.tdwg.org/dwc/terms/measurementValue = http://eol.org/schema/terms/yes
http://rs.tdwg.org/dwc/terms/measurementValue = http://eol.org/schema/terms/yes
http://rs.tdwg.org/dwc/terms/occurrenceID = http://eol.org/resources/804/occurrences/zoopilus_echinatus dana,_1846
http://eol.org/schema/measurementOfTaxon = http://eol.org/schema/terms/true
http://rs.tdwg.org/dwc/terms/scientificName = Zoopilus echinatus Dana, 1846
http://eol.org/schema/terms/resource = http://eol.org/resources/804

(the duplicates are there because of old/new data formats: one each...)

...So it wasn't harvested. I'll check the original source data...

**Comment by JRice** [comment]
BTW, developers can now get that information for any data point by doing something like:

``` ruby
trait = DataPointUri.find 9529372
trait.show_metadata
```

**Comment by JRice** [comment]
I can't check the original data... it's not on-disk and there's no pointer to it in the resource.  Looks like it's fallen into the void. ...I can't add the data without that... :S

Sorry, this has become a dead end.  ...What do you want me to do from here?

**Comment by jhammock** [comment]
Oops, here is the [original spreadsheet](https://www.dropbox.com/s/290g7j3f3hmtee1/scleractinia%20lifestye.xlsx?dl=0)

@jrice, did you just want to look, or do you need it as a DwC-A? I can send it to Eli if that is needed.

**Comment by JRice** [comment]
Sorry, I do need to see the DwC-A. :S  ...That could have been where it went AWOL, and if not, I would hate to miss it...

**Comment by jhammock** [comment]
note that this would be a newly created DwC-A. This resource was originally uploaded as a spreadsheet, back when that was possible. Does that mean we really don't have the information you need?

**Comment by JRice** [comment]
At the moment, we _really_ don't have the information for that field you're looking for. If it's in TraitBank, it's stored in a way that the code can't get to it... unless I've missed something (which is possible).  Are you sure we could see that metadata before the old code died? If so, I can pull up an old version of the code and try and figure it out...  But if not, I suspect it was never actually there... :S

**Comment by jhammock** [comment]
You mean we don't have the field at all, I expect, not just that it's missing in this resource? http://rs.tdwg.org/dwc/terms/measurementDeterminedBy, I presume. No problem; I'll put that info in another field. 

http://purl.org/dc/terms/source is a field we use frequently, definitely works in other resources, and was certainly showing in this one when first published. Shall I get a DwC-A from Eli and try a reharvest? If at least that field shows up on the next try, then we don't have a problem...

**Comment by JRice** [comment]
That's not actually what I meant, sorry.

A few things could have happened:
1. The data might have been missing from the original file.
2. The http://rs.tdwg.org/dwc/terms/measurementDeterminedBy field was encoded in a way that wouldn't have been read during harvesting.
3. Something weird about harvesting causes http://rs.tdwg.org/dwc/terms/measurementDeterminedBy to not be harvested. ...This would be weird.
4. Something weird about harvesting causes http://rs.tdwg.org/dwc/terms/measurementDeterminedBy to be _stored_ in a weird way such that my code can't see it in the old traitbank, and thus can't port it to the new one.
5. Something else which I couldn't predict (but I think this is actually unlikely, there's not much else that could go wrong, IMO).

All I meant to say is that I don't have access to the data right now. At all. It's either gone or was never there.

Please _do_ use http://rs.tdwg.org/dwc/terms/measurementDeterminedBy ...otherwise I won't be able to determine which of those went wrong!  :)

**Comment by jhammock** [comment]
OK, new [DwC-A](https://dl.dropboxusercontent.com/u/7597512/spreadsheets/resources/JenH/scleractinia_lifestye.tar.gz) is ready, listed in the harvest queue with annotation to check on this.

**Comment by JRice** [comment]
Okay. I see the file, thanks. I see the field, which is good, and I see the data (which all appear to be set to "Stephen D. Cairns"). I don't really see anything wrong here.

So, now I'm concerned that this wasn't the file that was actually processed when we harvested this resource. ...Could we re-harvest it using this file?

**Comment by jhammock** [comment]
I'm in favor of that. At best, this is "a DwC-A created from the original file" but I'm only assuming the spreadsheet is the original file because I found it in my TB resource files folder. But if we harvest this one and it works, then we don't have a problem, and that works for me...

**Comment by jhammock** [comment]
OK, this was reharvested, but alas, source and determinedBy metadata are still missing, eg: http://eol.org/pages/23255/data#data_point_44884713

**Comment by JRice** [comment]
Alas, I can see in the harvest log that it had trouble reaching Virtuoso, so a lot of data was lost. We'll have to re-harvest.

This is no good. Tramea harvesting should notice these kinds of errors and STOP to report them!

**Comment by jhammock** [comment]
Both fields now showing!
