### ISSUE TITLE
Richness scores wrong

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#27]
The values should be between 1-100, not 400 as it is on Tiger: http://eol.org/pages/328674/updates/statistics (for one example)

**Comment by AmrMMorad** [comment]
Well, I want to divide the solution into 4 main sections:

**How does Richness score task work:**
Richness scores rake task is working by doing calculations for taxa such as trusted images, trusted videos and etc. These calculations are written into a file tab separated. After all calculations are done, this file will be loaded into the database (table called "taxon_concept_metrics").

**The problem:**
Richness scores are completely wrong. I checked the calculations of the richness but is is done successfully even on staging server. I noticed that richness scores on production database are equivalent to total map count instead of richness score. This means that there is a tab missing in the file so when this file is loaded into the database table, richness took the element next to its correct value (and what is meant by next here is next value after the tab). 

**Why this happens now:**
After more investigations, I found that the problem is in BHL publications calculations. The code assumes that there will be a file called "taxon_concept_with_bhl_publications.txt", it tries to open this file to do the calculations but this file is missing on production. Current code RETURNS when the file is missing. This means that other calculations will be done without writing tab for BHL calculations place. Old code before wasn't doing a return meaning that when the file open process is failed, a tab is written into the calculations file and then continue other taxon calculations. 

**Final result:**
A tab is missing in the calculations file so richness scores are wrong. Either we need to write a tab (remove the RETURN in BHL calculations) in order to be reflected successfully into taxon_concept_metrics table in the database or do more complicated solution to take care for what is written in the database table..
