### ISSUE TITLE
[3] Autocomplete not working on data search page: resolve conflict between autocomplete and attribute selector scripts

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#31]
Ken-ichi says: 

> Hey folks,
> 
> I've attached a screenshot of what I'm seeing (Chrome 45.0.2454.101
> (64-bit) on a Mac). Basically the trait name autocomplete is only
> searching on the beginning of the trait names, which is frustrating if
> you don't know what kind of traits are available, and the taxon
> autocomplete does not seem to be working at all. Filling those in with
> names that _should_ work and clicking "Search" does turn up results
> (or an appropriate lack of results), e.g.
> http://eol.org/data_search?utf8=%E2%9C%93&taxon_concept_id=&attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVT_0001259&commit=Search&taxon_name=Cirripedia&q=&min=&max=&unit=&sort=desc,
> but given the warning that "ONLY selections from the drop-down will be
> used, do not edit the text without selecting a result," that was not
> my expectation.
> 
> For context, I was trying to find out what the biggest barnacle
> species in world is, which TraitBank seems well-suited to do, assuming
> you have the data, but it doesn't seem like you do.
> <img width="1268" alt="kichi" src="https://cloud.githubusercontent.com/assets/24174/10460629/23ca9de6-71a3-11e5-9c19-ba036a934160.png">

**Comment by HudaSoliman** [comment]
The fix is found on this branch: https://github.com/EOL/eol/compare/git31-autocomplete_bug
A screenshot for a working attribute selector ( auto-completes on all the tokens) : 
![attr-selector](https://cloud.githubusercontent.com/assets/10114312/11168703/bea055f8-8ba3-11e5-8092-30d73fae3cc2.png)

A screenshot for a working auto-complete: 
![screenshot from 2015-11-15 14 11 32](https://cloud.githubusercontent.com/assets/10114312/11168701/b7cc326a-8ba3-11e5-83b5-2cb771c53f99.png)
